#!/usr/bin/env python3
from termcolor import colored
import sys
import helpers
from analyzer import Analyzer
# TODO
def main():
    if len(sys.argv) != 2:
        print("Usage: ./tweets @screen_name")
        exit(1)
    tweets = helpers.get_user_timeline(sys.argv[1], 50)

    if tweets == None:
        print("{} not exists or is a private count.".format(sys.argv[1]))
        exit(1)
    a = Analyzer('positive-words.txt', 'negative-words.txt')
    for tweet in tweets:
        tmp = a.analyze(tweet)
        if tmp > 0:
            print(colored("{} {}".format(tmp, tweet), "green"))
        elif tmp < 0:
            print(colored("{} {}".format(tmp, tweet), "red"))
        else:
            print(colored("{} {}".format(tmp, tweet), "yellow"))



if __name__ == "__main__":
    main()